apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service-deployment
spec:
  selector:
    matchLabels:
      name: user-service
  template:
    metadata:
      labels:
        name: user-service
        prometheus: monitoring
    spec:
      containers:
        - name: user-service
          image: zalerix/thesis-user-service:latest
          livenessProbe:
            httpGet:
              port: 9000
              path: /actuator/health/liveness
          readinessProbe:
            httpGet:
              port: 9000
              path: /actuator/health/readiness
          lifecycle:
            preStop:
              exec:
                command: [ "sh", "-c", "sleep 5" ]
          resources:
            limits:
              cpu: "1000m"
              memory: "256Mi"
            requests:
              cpu: "100m"
              memory: "256Mi"
          ports:
            - containerPort: 8080
              name: app-port
            - containerPort: 9000
              name: actuator-port
          envFrom:
            - configMapRef:
                name: user_service-properties
            - secretRef:
                name: common-secrets