apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  environment: production

resources:
  - ../../base

components:
  - ../../components/zipkin

configMapGenerator:
  - name: user_service-env
    envs:
      - user-service/config.properties

secretGenerator:
  - name: common-sercrets
    envs:
      - secrets.properties
