apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-to-gateway
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  rules:
    - http:
        paths:
          - path: /metrics(/|$)(.*)
            pathType: Prefix
            backend:
              service:
                name: grafana-url
                port:
                  number: 3000
          - path: /zipkin(/|$)(.*)
            pathType: Prefix
            backend:
              service:
                name: zipkin-url
                port:
                  number: 9411
          - path: /api(/|$)(.*)
            pathType: Prefix
            backend:
              service:
                name: api-gateway-url
                port:
                  number: 8080
  ingressClassName: nginx