apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- api-gateway/deployment.yaml
- api-gateway/cluster-ip.yaml
- api-gateway/ingress.yaml
- api-gateway/hpa.yaml
- user-service/deployment.yaml
- user-service/cluster-ip.yaml
- user-service/hpa.yaml
- knowhere-frontend/deployment.yaml
- knowhere-frontend/cluster-ip.yaml
- knowhere-frontend/hpa.yaml
- knowhere-frontend/ingress.yaml

images:
- name: zalerix/knowhere-frontend:latest
  newName: zalerix/knowhere-frontend
  newTag: 0.0.0
- name: zalerix/thesis-api-gateway:latest
  newName: zalerix/thesis-api-gateway
  newTag: 1.9.0
- name: zalerix/thesis-knowhere-frontend:latest
  newName: zalerix/thesis-knowhere-frontend
  newTag: 0.1.0
- name: zalerix/thesis-user-service:latest
  newName: zalerix/thesis-user-service
  newTag: 1.3.0
