apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- api-gateway-deployment.yaml
- api-gateway-ip.yaml
- api-gateway-ingress.yaml
- api-gateway-hpa.yaml

images:
- name: zalerix/thesis-api-gateway:latest
  newName: zalerix/thesis-api-gateway
  newTag: 1.5.1
